---
title: "class_1/29_functions"
author: "lisa liubovich"
date: "2024-01-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

# Functions

```{r}
# A function is a structured and sequenced set of commands 
# that process input values to produce output values efficiently.
# A function reduces repetitive calculations that often result 
# in mistakes, errors, and unneeded work.

# Consider the task of calculating the volume of twenty 
# cylinders with the given dimensions:
# Cylinder1  r = 4, h = 6      V = pi(4^2)(6)
# Cylinder2  r = 3, h = 10     V = pi(3^2)(10)
# Cylinder3  r = 2.5, h = 5    V = pi((2.5)^2)(5)
# Cylinder4  r = 12, h = 4     V = pi(12^2)(4)
# Cylinder5  r = 20, h = 14    V = pi(20^2)(16)
#            .
#            .
#            .
# Cylinder20 r = 12.25, h = 9  V = pi(12.25)(9)

# The formula V = pi(r^2)h would have to be applied correctly 
# 20 times, if you are to do these manually; one at a time.  
# There is certainly a high risk for errors i.e. data entry 
# or misuse of the formula for a problem.
 
# Were any errors committed in the executions above ? Cylinder 5 and 20 have an error --> doing things thru brute force increases the probability of human error, which is why we use functions (to minimize the probability of human error)
 
# We now use a function for this problem to reduce repetitive
# calculations and possible errors
 
# Basic function structure:
 
# function_name <- function (argument/input variables) {
# statements/expression for calculation/equation          
#  }

# Call the function and evaluate


# Example 1 Write a function to find the volume of a cylinder

#  Volume = pi(r^2)h,  pi is approximately 3.14

volume_cylinder <- function(r, h) {
 pi*r^2*h # expression of execution
}

volume_cylinder(4, 6)
```

```{r}
# this function can now be used for multiple tasks
volume_cylinder(3, 10)
```

```{r}
# Now lets add a descriptive statement for the output

# Example 2
volume_cylinder <- function(r, h) {
  V = pi*r^2*h
  print(paste("The volume of a cylinder with a radius of 4 and
              a height of 6 is",V))
  
}

volume_cylinder(4, 6)

# \n means next line

# this answer is correct and accurate, but it can be enhanced by rounding
```

```{r}
# Now lets produce an answer that is rounded to a specified value

# Example 3
volume_cylinder <- function(r, h) {
  V = pi*r^2*h
  print(paste("The volume of a cylinder with a radius of 4 and 
              a height of 6 is", 
              round(V, digits = 3))) # digits after decimal
  
}

volume_cylinder(4, 6)
```

```{r}
# Example 4

# function to print x raised to the power y

# x is base, y is power/exponent
pow <- function(x, y) {
  result <- x^y # set expression of execution to result
  print(paste(x,"raised to the power", y, "is", result))
}

pow(8, 2)
```

```{r}
pow(2,8)

# can be input in different ways, ex: pow(x = 2, y - 8). will get the same result

# if you designate the value for one variable and not for the other, it is implied that the second value is the value of the second variable
```

```{r}
# Example 5a

# Write a function that will create the first 10 squares of
# positive odd integers. That is your function will give you 
# the following output. 1, 9, 25, 49, ., 361 when you input 
# values 1 to 10.

# How do you write a positive odd integer?  2*x - 1 ,  where x 
# is positive integer


# Method 1

C <- function(x) { # x is input variable
  (2*x - 1)^2 # expression of execution
}

C(1:10) # will give us only the first ten

# efficiency is top priority, which is often accomplished by shorter code

```

```{r}
# Method 2
C <- function(x) {
  (2*x - 1)^2
  return((2*x - 1)^2) # some ppl (mainly computer science people) use the return in the expression of execution because they probably learned python first and you need to use return in python
  
} 

C(1:10)

# you want to develop your own particular style for coding; there are many ways to correctly get a result
```
# If else statements
```{r}
# Using our function how could we get results for C2 ?



# The If else statement

#if (condition) {
#  Expr1  (execute expression or command 1)
#} else {
#  Expr2  (execute expression or command 2)
#}

# if the condition is met, you have a certain output. if it isn't met, you have another output. 

# Example 6

# Set the if-else statement
quantity <- 13  # indicate a quantity to process
if (quantity > 20) {
  print('You sold a lot!')
} else {
  print('Not enough for today')  
}

# in this scenario, 13 does not meet the condition therefore the else expression is the one that is executed
```

```{r}
# Example 7  (Let's write a function that will test for 
# divisibility)

# Is 125 divisible by 3?

# right away we can see that it isn't because 1+2+5 = 8 and 8 isn't divisible by 3

# Method 1
x<-125
if (x %% 3 == 0) { # if you divide x by 3 and the remainder is 0
  print("the number is divisible by 3")
} else {
  print("the number is not divisible by 3")
}
```

```{r}
# Method 2
FunctionA <- function(x)  
  if (x %% 3 == 0) {
    print("the number is divisible by 3")
  } else {
    print("the number is not divisible by 3")
  }
  
FunctionA(125)

# more consistent with the coding we've done up to this point
```

```{r}
FunctionA(2112)

# consistent with the rule for 3
```

```{r}
# Multiple Conditions  / else if

# if
# else if
# else

# Example 8
# Write a function that will give a result for three conditions: 
# x > 0, x < 0, and x = 0.

check <- function(x) {
  if (x > 0) {
    result <- "Positive"
  }
  else if (x < 0) {
    result <- "Negative"
  }
  else {
    result <- "Zero"
  }
  return(result)
}

check(-3)

```

```{r}
check(32)
check(0)
```

```{r}
# Example 9

# Create vector quantity
quantity <-  26
# Create multiple condition statement
if (quantity <20) {
  print('Not enough for today')
} else if (quantity > 20  & quantity <= 30) {
  print('Average day')
} else {
  print('What a great day!')
}
```
# for loops
```{r}
# Using for loops

#For (i in vector) {
#   Exp 
#   }

# Example 1  (Write a for loop that will cube each integer
#             from 1 to 4 inclusive)

for ( i in 1:4) { # iterate from 1 to 4
  print (i^3) # cube each number
  }
```
```{r}
# Example 2  values are NOT consecutively ordered
# Write a for loop that will cube the following values
# -2,4,7,-1

for (i in c(-2,4,7,-1)) { # numbers are vectorized, so we concatenate the vector
  print (i^3)
}
```
```{r}
# Example 3  

# Changing Kilometers to miles using a for loop
# Write a for loop that will convert km measurements
# of 12,20,45,80,and 110 to miles

for (km in c(12,20,45,80,110)) {
  print(c(km, .621371*km)) # conversion of km to mi; need the same concatenated vector construction
}

# for each km value, multiply it by the factor
```
# alternative methods for operating on a data table

```{r}
# Consider the following tibble. Use two methods to find 
# the median of each column.
 

 df <- tibble(
   a = rnorm(50),
   b = rnorm(50),
   c = rnorm(50),
   d = rnorm(50)
 )
 df
```
```{r}
# method 1  
 
median(df$a)
median(df$b)
median(df$c)
median(df$d)

# this method works, but it isn't very efficient
```
```{r}
# method 2  The "Special For Loop Method"
 
 output <- vector("double", ncol(df))  # 1. output
 for (i in seq_along(df)) {            # 2. sequence
   output[[i]] <- median(df[[i]])      # 3. body
 }
 output
 
 # variables are all doubles
 # data source is df
 # iterate across columns 
```

```{r}
mtcars<- mtcars
```

```{r}
output2 <- vector("double", ncol(mtcars))
for (i in seq_along(mtcars)) {
  output2[[i]] <- mean(mtcars[[i]])
}
output2

# more efficient; calculates mean across all columns
```

```{r}
diamonds <- diamonds
```

```{r}
output3 <- vector("double", ncol(diamonds))  # 1. output
 for (i in seq_along(diamonds)) {            # 2. sequence
   output3[[i]] <- mean(diamonds[[i]])      # 3. body
 }

output3
# iterates along the columns to find the mean of each column

# we get some NAs because some of the columns are categorical
```

