---
title: "final_exam"
author: "lisa liubovich"
date: "2024-05-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading packages}
library(tidyverse)
library(data.table)
```

# 2.

```{r 2a}
flights3 <- fread("./nycdata.csv")
```

```{r 2b}
flights3[, .(origin, dest, carrier)]
```

```{r 2c}
flights3[origin == "JFK" & dest == "SEA" & carrier == "DL"]
```

```{r 2d}
flights3[, !c("air_time")]
```

```{r 2e}
flights3[, .(mindist = min(distance), maxdist = max(distance))]
```

```{r 2f}
# the following output shows the mean distance for each carrier. The carriers are listed in alphabetical order.

f <- flights3[, .(mean_distance = mean(distance)), by = .(carrier)][1:13]

View(f)
```

# 4.

```{r 3 packages}
install.packages("tm")  
install.packages("SnowballC") 
install.packages("wordcloud")  
install.packages("RColorBrewer")

library("tm")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")
```

```{r 3 creating my text file}

text <- "It is literally impossible to be a woman. You are so beautiful, and so smart, and it kills me that you don't think you're good enough. Like, we have to always be extraordinary, but somehow we're always doing it wrong.

You have to be thin, but not too thin. And you can never say you want to be thin. You have to say you want to be healthy, but also you have to be thin. You have to have money, but you can't ask for money because that's crass. You have to be a boss, but you can't be mean. You have to lead, but you can't squash other people's ideas. You're supposed to love being a mother, but don't talk about your kids all the damn time. You have to be a career woman but also always be looking out for other people.

You have to answer for men's bad behavior, which is insane, but if you point that out, you're accused of complaining. You're supposed to stay pretty for men, but not so pretty that you tempt them too much or that you threaten other women because you're supposed to be a part of the sisterhood.

But always stand out and always be grateful. But never forget that the system is rigged. So find a way to acknowledge that but also always be grateful.

You have to never get old, never be rude, never show off, never be selfish, never fall down, never fail, never show fear, never get out of line. It's too hard! It's too contradictory and nobody gives you a medal or says thank you! And it turns out in fact that not only are you doing everything wrong, but also everything is your fault.

I'm just so tired of watching myself and every single other woman tie herself into knots so that people will like us. And if all of that is also true for a doll just representing women, then I don't even know."


file_path <- file.path("~/Desktop/grad_school/spring_2024/data_613/lab", "gloriaspeechbarbie.txt")


writeLines(text, file_path)

```

```{r}
filePath <- "../lab/gloriaspeechbarbie.txt"
text <- readLines(filePath)
docs <- Corpus(VectorSource(text))

inspect(docs)

toSpace <- content_transformer(function (x , pattern ) gsub(pattern, " ", x))
docs <- tm_map(docs, toSpace, "/")
docs <- tm_map(docs, toSpace, "@")
docs <- tm_map(docs, toSpace, "\\|")

# cleaning text
# Convert the text to lower case
docs <- tm_map(docs, content_transformer(tolower))
# Remove numbers
docs <- tm_map(docs, removeNumbers)
# Remove english common stopwords
docs <- tm_map(docs, removeWords, stopwords("english"))
# Remove your own stop word
# specify your stopwords as a character vector
docs <- tm_map(docs, removeWords, c("blabla1", "blabla2")) 
# Remove punctuations
docs <- tm_map(docs, removePunctuation)
# Eliminate extra white spaces
docs <- tm_map(docs, stripWhitespace)
# Text stemming
# docs <- tm_map(docs, stemDocument)

# Let's create a Term Document Matrix

dtm <- TermDocumentMatrix(docs)
m <- as.matrix(dtm)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)
head(d, 10)

# Now Let's create the Word Cloud !!

set.seed(1234)
wordcloud(words = d$word, freq = d$freq, min.freq = 1,
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))

```

# 5.

```{r 5}
matrix = matrix(nrow=5, ncol=5)
for(i in 1:nrow(matrix))
{
  for(j in 1:ncol(matrix))
  {
    matrix[i,j] = (i + j)^3
  }
}
print(matrix)
```
