---
title: "hw_3"
author: "lisa liubovich"
date: "2024-02-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

# 1.

```{r vector 1}
Vector1 <- (c(10,19,121,83,63,7,77,61,51,97,123,41))
Vector1
```

```{r 1}
# method 1:
Vector1[c(1, 12)]

# method 2:
Vector1[c(-2:-11)]
```

# 2.

```{r 2}
# method 1:
Vector1[Vector1 < 60]

# method 2:
Vector1[!(Vector1 > 60)]
```

# 3.

```{r}
# method 1:
Vector1[!(Vector1 %% 2 == 0 | Vector1 %% 3 == 0)]

# method 2:
Vector1[Vector1 %% 2 !=0 & Vector1 %% 3 !=0]
```

# 4.

```{r 4}
# method 1:
Vector1[is.na(Vector1)]

# method 2:
Vector1[!is.na(Vector1)]
```

# 5.

```{r list}
myList <- list(TRUE, 12.35, "pear", 48, c = 3:8, list(23, "team"))
myList
```

```{r 5}
str(myList[(3)])
```

# 6.

```{r 6}
myList[1:3]
```

# 7.

```{r 7}
myList2 <- list(TRUE, 12.35, b= "pear", 48, c = 3:8, list(23, "team"))
myList2$b
```

# 8.

```{r 8}
quadratic <- function(a,b,c) {
  discriminant <- b^2 - 4 * a * c
  if (discriminant < 0) {
    return("no real roots")
  } else {
    root1 <- (-b + sqrt(discriminant)) / (2 * a)
    root2 <- (-b - sqrt(discriminant)) / (2 * a)
    return(c(root1, root2))
  }
}

quadratic(1, -3, -28)
quadratic(1, 1, -30)
quadratic(3, 14, 8)
quadratic(2, 11, 6)
```
