---
title: "lab_03"
author: "lisa liubovich, melanie klein"
date: "2024-02-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse) 
library(dplyr)
```

```{r}
x <- list(2, 4, 5, 9, 1)
y <- list(8, 7, 2, 8, 3)
z <- list(1, 8, 5, 4, 2)
```

# 1.

```{r}
pmap_dbl(list(x, y, z), function(x, y, z) (x + y + z)**2)
```

```{r}
tribble( ~Student,  ~Gender,    ~Salary,
                   "John",   "Male",       65000,
                   "Alice",  "Female",    73000,
                    "Juan",   "Male",       66000,
                    "Beth",  "Female",    71500,
                    "Denise", "Female",  82000
) -> table
table
```

# 2.

```{r}
table %>%
  pmap_chr(~ str_glue("{..1} who is {..2}, has a salary that is {..3} dollars per year."))
```

# 3.

```{r}
z <- matrix( nrow = 5, ncol = 5)
for (m in 1:5) {
  for (n in 1:5) {
    z[m, n] <- m + n
  }
}
print(z)
```

# 4.

```{r}
x <- c(1:20)
for (val in x) {
  if (val == 5 | val == 10) {
    next
  }
  print(val)
}
```

Thank you to Melanie Klein for helping me with this lab while I wasn't feeling well.
