---
title: "practice_midterm_lab"
author: "lisa liubovich"
date: "2024-03-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# 1.

```{r}
decrease_root <- function(x){
  if (x <= 0) {
    print("number must be positive")
    return(NULL)
  }
  result <- (x - sqrt(x))
  return(result)
}

decrease_root(100)
```

# 2.

```{r}
volume_cylinder <- function(r, h) {
 pi*r^2*h
}

sa_cylinder <- function(r,h) {
  (2 * pi * r * h) + (2 * pi * r^2)
}

volume_cylinder(10, 4.5)
sa_cylinder(10, 4.5)
```

# 3.

```{r}
number <- 153
if (number %% 9 == 0) {
  print("this number is divisble by 9")
} else {
  print("this number is not divisible by 9")
}
```

```{r}
number <- 2009
if (number %% 9 == 0) {
  print("this number is divisble by 9")
} else {
  print("this number is not divisible by 9")
}
```

# 4.

```{r}
for (i in 10:1) {
  print(i^3 - i^2)
}
```

# 5.

```{r}
U <- c("Maine", "Texas", "Delaware", "Oregon", "Utah", "Vermont", "Ohio")
U
```

## a. 

U is an atomic vector because it is homogeneous (made up entirely of strings).

## b.

```{r}
U[c(1,6)]
```

## c.

```{r}
U[-2]
```

## d.

```{r}
length(U)
```

# 6.

```{r}
V = list("Chicago", k = list(2, 6, 18, 24), FALSE, 13, 1.3, y = 1:10)
V
```

## a.

Vector V is a list because it contains heterogeneous elements (such as strings, integers, logicals, etc).

## b.

```{r}
str(V[5])
```

## c.

```{r}
str(V[])
```

# 7.

```{r}
tribble( ~John, ~Raymond, ~Martha, ~Alice, ~Juan,
86, 77, 81, 88, 90,
79, 78, 85, 81, 78,
76, 75, 88, 94, 81,
84, 90, 71, 84, 89,
100, 80, 93, 85, 84,
90, 73, 70, 88, 93,
) -> TestScores
TestScores
```

## a.

```{r}
map_dbl(TestScores, median)
```

## b.

```{r}
map(TestScores, ~. ^(1/3))
```

## c.

```{r}
convert0 <- function(x) {
  return(0)
}

TestScores_0 <- map_df(TestScores, convert0)
TestScores_0
```

# 8.

```{r}
z <- matrix(nrow = 3, ncol = 4)
for (m in 1:3) {
  for (n in 1:4) {
    z[m, n] <- -1*(m + n)^2
  }
}

print(z)
```

# 9.

```{r}
data(midwest)
```

```{r}
midwest %>% 
  select(state, county, area, percollege) %>%
  filter(state == "WI") %>% 
  mutate(state = ifelse(state == "WI", "Wisconsin", state)) %>% 
  head(n = 20)
  
```
